[project]
name = "chat"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]

license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi (>=0.116.1,<0.117.0)",
    "uvicorn[standard] (>=0.35.0,<0.36.0)",
    "sqlalchemy (>=2.0.42,<3.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "bcrypt (>=4.3.0,<5.0.0)",
    "pyjwt[crypto] (>=2.10.1,<3.0.0)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "alembic-postgresql-enum (>=1.8.0,<2.0.0)",
    "aio-pika (>=9.5.7,<10.0.0)",
    "aioredis (>=2.0.1,<3.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "celery[rabbitmq,redis] (>=5.5.3,<6.0.0)",
    "aiosmtplib (>=4.0.1,<5.0.0)",
    "email-validator (>=2.2.0,<3.0.0)",
    "dishka (>=1.6.0,<2.0.0)",
]

[tool.poetry]
package-mode = false
[tool.poetry.dependencies]
python = ">=3.10,<4.0"
[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
alembic = "^1.16.4"
pre-commit = "^4.3.0"
ruff = "^0.12.10"
pytest-asyncio = "^1.1.0"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = ["--import-mode=importlib"]
asyncio_mode = "auto"

[tool.ruff]
line-length = 88
target-version = "py311"

# Enable the formatter (Black-compatible)
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

# Linting configuration
[tool.ruff.lint]
# Common rule sets:
# E = pycodestyle (pep8 errors)
# F = pyflakes
# I = isort (import sorting)
select = ["E", "F", "I"]
ignore = ["E501"]        # ignore line-too-long, since formatter handles it

# Import sorting behavior (isort replacement)
[tool.ruff.lint.isort]
known-first-party = ["shared"] # replace with your package name
combine-as-imports = true
