"""add admin status to chat_user

Revision ID: 230e59e1c74e
Revises: 3a3fda7241d3
Create Date: 2025-08-07 18:20:48.388316

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "230e59e1c74e"
down_revision: Union[str, Sequence[str], None] = "3a3fda7241d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_users", sa.Column("is_admin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_users", "is_admin")
    # ### end Alembic commands ###
