"""update chat, message, user

Revision ID: 23475d85932f
Revises: c91a5d38b864
Create Date: 2025-08-07 00:01:01.360793

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "23475d85932f"
down_revision: Union[str, Sequence[str], None] = "c91a5d38b864"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
