"""add chat type to chat

Revision ID: 71b807c25e16
Revises: 9743ab255ab0
Create Date: 2025-08-09 23:10:49.701489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71b807c25e16'
down_revision: Union[str, Sequence[str], None] = '9743ab255ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRIVATE', 'GROUP', name='chat_type').create(op.get_bind())
    op.add_column('chats', sa.Column('type', postgresql.ENUM('PRIVATE', 'GROUP', name='chat_type', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'type')
    sa.Enum('PRIVATE', 'GROUP', name='chat_type').drop(op.get_bind())
    # ### end Alembic commands ###
