"""make user_id field unique in email_verification

Revision ID: b1253d56eba3
Revises: a0cd98e13fae
Create Date: 2025-08-25 16:59:34.664756

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1253d56eba3"
down_revision: Union[str, Sequence[str], None] = "a0cd98e13fae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "email_verifications", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "email_verifications", type_="unique")
    # ### end Alembic commands ###
