"""add send_at field to email_verification

Revision ID: ef420ff05103
Revises: b1253d56eba3
Create Date: 2025-08-25 17:16:34.032277

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef420ff05103"
down_revision: Union[str, Sequence[str], None] = "b1253d56eba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_verifications",
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_verifications", "sent_at")
    # ### end Alembic commands ###
